pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                //git 'https://github.com/maan98/jenkinsdemos.git'
                sh 'mvn -B compile'
            }
        }
         stage('Test') { 
            steps {
                sh 'mvn test'
            }
        }
        stage('Package') { 
            steps {
                sh 'mvn package'
            }
        }
    }
}
