pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                git 'https://github.com/maan98/jenkinsdemos.git'
                bat 'mvn -B compile'
            }
        }
        
    }
}
